add Production Infrastructure

diff --git a/jenkins/Jenkinsfile.ci b/jenkins/Jenkinsfile.ci
--- a/jenkins/Jenkinsfile.ci
+++ b/jenkins/Jenkinsfile.ci
@@ -52,6 +52,17 @@ pipeline {
                 '''
             }
         }
+        
+        stage('Snyk Auth') {
+            steps {
+                sh '''
+                    if ! command -v snyk &> /dev/null; then
+                        npm install -g snyk
+                    fi
+                    snyk auth $SNYK_TOKEN || echo "Snyk auth failed - continuing without auth"
+                '''
+            }
+        }
 
         stage('Test Services in Parallel') {
             parallel {
